"""
Quality Gate & Speculative Escalation Nodes for LangGraph.
Implements:
1. Fast heuristic/schema/confidence Quality Gate decision router.
2. Speculative Refinement Escalator (passes Flash's draft directly to Pro without re-ingesting raw context).
3. Composite-namespaced Cache Writeback with Granular Turn Telemetry.
"""

from typing import Any, Dict, Literal
import time
from app.graph.state import InterviewState
from app.llm.client import get_llm_client
from app.cache.semantic_cache import get_semantic_cache


def quality_gate_decision(state: InterviewState) -> Literal["pro_escalator_node", "cache_writeback_node"]:
    """
    Conditional Edge: Evaluates Gemini Flash output with sub-millisecond overhead.
    Triggers Gemini Pro escalation on schema invalidity, low confidence, or flagged uncertainty.
    """
    # 1. Pure Cache Hits never escalate
    if state.get("cache_hit"):
        return "cache_writeback_node"

    cur_eval = state.get("current_evaluation", {})

    # 2. Schema Validation: Score must be numeric and feedback must be substantial
    if "score" not in cur_eval or not isinstance(cur_eval.get("score"), (int, float)):
        return "pro_escalator_node"

    feedback = str(cur_eval.get("feedback", "")).strip()
    if len(feedback) < 20:
        return "pro_escalator_node"

    # 3. Model Confidence Threshold
    confidence = float(cur_eval.get("confidence", 0.90))
    if confidence < 0.72:
        return "pro_escalator_node"

    # 4. Uncertainty Flags: Presence of conceptual contradictions or ambiguous boundaries
    uncertainty_flags = cur_eval.get("uncertainty_flags", [])
    if uncertainty_flags and len(uncertainty_flags) > 0:
        return "pro_escalator_node"

    # 5. Difficulty / Borderline Threshold on Hard Topics
    score = float(cur_eval.get("score", 10.0))
    difficulty = str(state.get("difficulty", "medium")).lower()
    if difficulty == "hard" and score < 5.0:
        return "pro_escalator_node"

    return "cache_writeback_node"


def pro_escalator_node(state: InterviewState) -> Dict[str, Any]:
    """
    Node: Speculatively refines Flash's draft evaluation using Gemini 2.5 Pro.
    Avoids double inference overhead by passing Flash's draft critique directly
    instead of re-running raw document retrieval or heavy context ingestion.
    """
    history = list(state.get("graph_history", []))
    history.append("pro_escalator_node")

    client = get_llm_client()
    q = state.get("current_question", "")
    ans = state.get("candidate_answer", "")
    draft = state.get("flash_draft_evaluation", {})

    # Speculative verification prompt: Focuses Pro's reasoning on the draft delta
    prompt = f"""
    [SPECULATIVE VERIFICATION TASK - GEMINI PRO]
    You are a Principal Evaluator verifying a draft evaluation generated by a fast model.
    
    QUESTION: {q}
    CANDIDATE ANSWER: {ans}
    
    FLASH DRAFT EVALUATION:
    - Draft Score: {draft.get('score', 'N/A')}/10
    - Model Confidence: {draft.get('confidence', 'N/A')}
    - Identified Correct Points: {draft.get('correct_points', [])}
    - Identified Missing Points: {draft.get('missing_concepts', [])}
    - Flagged Uncertainties: {draft.get('uncertainty_flags', [])}
    - Draft Feedback: {draft.get('feedback', '')}
    
    INSTRUCTIONS:
    1. Verify whether the draft critique accurately identified technical misconceptions or missing invariants.
    2. Resolve the flagged uncertainties and provide the final verified evaluation.
    
    Return JSON with:
    - score: (float 0.0 to 10.0)
    - confidence: (float 0.0 to 1.0)
    - correct_points: (list of strings)
    - missing_concepts: (list of strings)
    - incorrect_points: (list of strings)
    - feedback: (string with detailed, actionable advice)
    - ideal_answer: (string)
    """

    res = client.generate_json(prompt=prompt, model_tier="pro")
    data = res.get("data", {})
    data["model_used"] = "pro"
    data["cache_hit"] = False
    data["escalated"] = True
    data["ttft_ms"] = res.get("ttft_ms", 520.0)
    data["generation_latency_ms"] = res.get("generation_latency_ms", 950.0)
    data["latency_ms"] = res.get("latency_ms", 1470.0)

    # Determine escalation reason
    conf = float(draft.get("confidence", 1.0))
    flags = draft.get("uncertainty_flags", [])
    if conf < 0.72:
        reason = f"low_flash_confidence_{conf:.2f}"
    elif flags:
        reason = "flagged_conceptual_uncertainty"
    else:
        reason = "quality_gate_hard_score_boundary"

    return {
        "current_evaluation": data,
        "model_used": "pro",
        "escalated": True,
        "escalation_reason": reason,
        "active_node": "pro_escalator_node",
        "graph_history": history,
        "total_input_tokens": state.get("total_input_tokens", 0) + res.get("input_tokens", 260),
        "total_output_tokens": state.get("total_output_tokens", 0) + res.get("output_tokens", 320),
    }


def cache_writeback_node(state: InterviewState) -> Dict[str, Any]:
    """
    Node: Persists verified evaluation to composite semantic cache
    and records granular per-turn telemetry.
    """
    history = list(state.get("graph_history", []))
    history.append("cache_writeback_node")

    cur_eval = dict(state.get("current_evaluation", {}))
    cur_eval["round_number"] = state.get("round_number", 1)
    cur_eval["topic"] = state.get("current_topic", "")
    cur_eval["question_id"] = state.get("question_id", "q0")
    cur_eval["question"] = state.get("current_question", "")
    cur_eval["candidate_answer"] = state.get("candidate_answer", "")

    # Calculate Granular Per-Turn Telemetry
    retrieval_lat = float(state.get("retrieval_latency_ms", 12.0))
    cache_lookup_lat = float(state.get("cache_lookup_latency_ms", 1.2))
    
    is_hit = bool(state.get("cache_hit", False))
    is_escalated = bool(state.get("escalated", False))

    if is_hit:
        # Cache HIT: pipeline short-circuited at semantic_cache_check_node.
        # retrieval_node, evaluate_answer_node, and all LLM calls were never invoked.
        # E2E latency = cache lookup time only (in-memory vector dot product).
        ttft = 0.0
        gen_lat = 0.0
        eval_lat = 0.0
        e2e_lat = cache_lookup_lat  # retrieval_lat is 0.0 — RAG never ran
    elif is_escalated:
        # Flash pass + Pro refinement
        flash_lat = float(state.get("flash_draft_evaluation", {}).get("latency_ms", 490.0))
        pro_eval = state.get("current_evaluation", {})
        ttft = float(pro_eval.get("ttft_ms", 520.0))
        gen_lat = float(pro_eval.get("generation_latency_ms", 950.0))
        eval_lat = flash_lat + (ttft + gen_lat)
        e2e_lat = retrieval_lat + cache_lookup_lat + eval_lat
    else:
        # Flash direct
        flash_eval = state.get("current_evaluation", {})
        ttft = float(flash_eval.get("ttft_ms", 210.0))
        gen_lat = float(flash_eval.get("generation_latency_ms", 280.0))
        eval_lat = ttft + gen_lat
        e2e_lat = retrieval_lat + cache_lookup_lat + eval_lat

    turn_telemetry = {
        "cache_lookup_latency_ms": round(cache_lookup_lat, 2),
        "retrieval_latency_ms": round(retrieval_lat, 2),
        "ttft_ms": round(ttft, 2),
        "generation_latency_ms": round(gen_lat, 2),
        "end_to_end_turn_latency_ms": round(e2e_lat, 2),
        "cache_hit": is_hit,
        "escalated": is_escalated,
        "model_used": state.get("model_used", "flash"),
    }

    # Persist to semantic cache if not a cache hit and not bypassed
    if not is_hit and not state.get("cache_bypassed", False):
        cache = get_semantic_cache()
        ans = state.get("candidate_answer", "")
        cache.insert(
            query=ans.strip(),
            response=cur_eval,
            track_id=state.get("current_topic", "general"),
            question_id=state.get("question_id", "q0"),
            rubric_version=state.get("rubric_version", "v1"),
        )

    eval_history = list(state.get("evaluations", []))
    eval_history.append(cur_eval)

    current_round = state.get("round_number", 1)
    max_rounds = state.get("max_rounds", 3)
    is_done = current_round >= max_rounds

    return {
        "evaluations": eval_history,
        "round_number": current_round + 1 if not is_done else current_round,
        "is_complete": is_done,
        "turn_telemetry": turn_telemetry,
        "end_to_end_turn_latency_ms": round(e2e_lat, 2),
        "active_node": "cache_writeback_node",
        "graph_history": history,
    }
